Project1:对文件diabetes.csv中的数据进行处理，将文件夹pima-diabetes放在E：盘的input文件夹下

In [1]:
from pandas import *
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib notebook
from scipy.stats import mode

import os
print(os.listdir("E:/input"))

['pima-diabetes']

In [3]:
################################读入diabetes.csv文件到diabetes################################### 
diabetes = pd.read_csv('E:/input/pima-diabetes/diabetes.csv')
################################读入diabetes.csv文件到diabetes###################################

In [4]:
################################显示diabetes的前5行################################### 
#diabetes.head(5)
print(diabetes.tail(16))
print(diabetes.head(10))
################################显示diabetes的前5行###################################

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
752            3      108             62             24        0  26.0
753            0      181             88             44      510  43.3
754            8      154             78             32        0  32.4
755            1      128             88             39      110  36.5
756            7      137             90             41        0  32.0
757            0      123             72              0        0  36.3
758            1      106             76              0        0  37.5
759            6      190             92              0        0  35.5
760            2       88             58             26       16  28.4
761            9      170             74             31        0  44.0
762            9       89             62              0        0  22.5
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age  Outcome
752                     0.223   25        0
753                     0.222   26        1
754                     0.443   45        1
755                     1.057   37        1
756                     0.391   39        0
757                     0.258   52        1
758                     0.197   26        0
759                     0.278   66        1
760                     0.766   22        0
761                     0.403   43        1
762                     0.142   33        0
763                     0.171   63        0
764                     0.340   27        0
765                     0.245   30        0
766                     0.349   47        1
767                     0.315   23        0
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6
1            1       85             66             29        0  26.6
2            8      183             64              0        0  23.3
3            1       89             66             23       94  28.1
4            0      137             40             35      168  43.1
5            5      116             74              0        0  25.6
6            3       78             50             32       88  31.0
7           10      115              0              0        0  35.3
8            2      197             70             45      543  30.5
9            8      125             96              0        0   0.0

   DiabetesPedigreeFunction  Age  Outcome
0                     0.627   50        1
1                     0.351   31        0
2                     0.672   32        1
3                     0.167   21        0
4                     2.288   33        1
5                     0.201   30        0
6                     0.248   26        1
7                     0.134   29        0
8                     0.158   53        1
9                     0.232   54        1

Check for Summary Statistics

In [32]:
################################显示diabetes的详细信息，包括样本数、均值、方差等等################################## 
diabetes.describe()
################################显示diabetes的详细信息，包括样本数、均值、方差等等##################################

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [11]:
################################显示diabetes中Outcome列中每种值出现的次数################################## 
diabetes["Outcome"].value_counts()
################################显示diabetes中Outcome列中每种值出现的次数##################################

0    500
1    268
Name: Outcome, dtype: int64

### Check missing values

In [34]:
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [9]:
################################显示diabetes中所有列的标题名################################## 
diabetes.columns
################################显示diabetes中所有列的标题名##################################

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [12]:
################################显示diabetes中所有列的值里面为0的个数################################## 
print((diabetes[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']] == 0).sum())
################################显示diabetes中所有列的值里面为0的个数##################################

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
dtype: int64

In [37]:
################################将diabetes中所有列的值中为0的值替换为NaN################################## 
diabetes.loc[:,['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI']] = diabetes[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI']].replace(0, np.NaN)

################################将diabetes中所有列的值中为0的值替换为NaN################################## 
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,NaN,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [38]:
################################统计diabetes中所有列的值中为null的个数################################## 
diabetes.isnull().sum()
################################统计diabetes中所有列的值中为null的个数##################################

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

## Dealing with missing values

## A. Drop rows having NaN

In [ ]:
print("Size before dropping NaN rows",diabetes.shape,"\n")

################################将diabetes中包含NaN的行删掉################################## 
nan_dropped = diabetes.dropna()

################################将diabetes中包含NaN的行删掉################################## 
print(nan_dropped.isnull().sum())
print("\nSize after dropping NaN rows",nan_dropped.shape)

Size before dropping NaN rows (768, 9)

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

Size after dropping NaN rows (336, 9)

### **Project2、数据分析的一系列问题**

In [18]:
vector = np.random.chisquare(1,500)
print(vector)
################################打印vector的均值################################## 
print("Mean",np.mean(vector))
################################打印vector的均值################################## 

print("SD",np.std(vector))
print("Range",max(vector)-min(vector))

[6.41055074e-02 9.32655639e-01 6.12461198e-01 1.64992247e+00
 4.92867875e-01 7.52372169e-01 8.30592263e-02 5.94486483e-01
 1.37782822e-01 4.08739579e-03 2.31952212e+00 9.50355029e-02
 2.74125699e+00 2.45995466e+00 1.85958180e-02 5.44166305e-02
 2.11926280e+00 9.70466302e-05 8.05811697e-01 6.53963428e-02
 1.28767873e+00 7.41720384e-02 1.51876144e+00 2.00247197e+00
 4.20356121e-02 3.08095795e+00 3.84835299e-01 1.19896117e-01
 1.54636749e-01 2.39654257e+00 1.17071071e-02 2.39329815e+00
 1.45685249e+00 6.41352801e-01 2.17663904e-01 5.89968389e-01
 1.95899907e+00 1.42270618e-01 3.35307416e-02 1.78990775e-01
 4.08854936e-02 2.98120238e+00 1.15782546e+00 1.65149184e-01
 2.57912730e+00 1.96356601e+00 8.17773347e-02 7.62959169e-01
 4.06392382e-01 1.28191345e-02 1.01838715e+01 8.28659522e-01
 8.88565729e-01 3.48048877e-02 4.32762164e+00 2.17752514e-01
 2.81949450e-03 2.75308645e+00 2.39433025e+00 1.07990649e-01
 1.39397971e+00 2.01228930e+00 7.17738071e-01 1.46225240e+00
 2.88414797e-01 9.64639471e+00 4.54126226e-01 3.24651962e+00
 5.99947604e-01 6.25889413e-01 3.48604129e+00 1.90320997e+00
 2.01641537e-03 5.86846926e-01 1.14817300e-01 1.49232123e-01
 9.35366816e-02 1.79360002e-02 8.20263566e-02 5.62885047e+00
 2.72685279e+00 7.49782832e-01 3.54009440e+00 6.13452265e-02
 6.36037788e-01 3.98755393e-02 1.26441514e-04 1.13991272e-02
 1.11228008e+00 2.59075946e-01 1.10933350e+00 2.46878160e-01
 1.14079576e-02 3.14238223e+00 2.11673062e-01 1.23969929e+00
 9.09194947e-01 3.00803833e+00 1.47366328e+00 6.37124201e-02
 8.19410755e+00 7.64136376e-03 4.99649743e+00 5.42922621e-01
 4.23710829e-01 8.64663714e-01 2.39922542e-01 6.09645827e-02
 2.05889581e-02 2.39050178e-02 3.88609061e-01 2.52704692e+00
 1.37895763e+00 2.38368582e-01 5.67328294e-01 1.88664556e+00
 3.37266254e+00 1.11826721e+00 6.68965616e-01 2.35923917e-01
 3.48658751e-01 1.02360019e+00 2.50863609e-01 5.18400932e-01
 7.78416156e-02 8.92914558e-01 4.31436918e-01 2.13506439e-01
 3.17118199e-01 7.42492760e-02 1.72635098e+00 7.13886843e-01
 1.45266976e+00 2.31178588e+00 3.03333749e-01 5.00527918e-01
 3.69147746e-02 3.95365072e-01 1.49985859e-02 1.12401323e-02
 1.21700009e+00 3.45760675e-01 6.79043862e-02 1.11810825e+00
 1.79289469e-02 6.64136792e-01 5.60966251e-03 4.92739684e-01
 8.24405818e-03 2.33338513e-01 1.98380187e-02 9.94799728e-02
 1.04659861e-01 9.89122608e-01 5.91547244e-01 2.05265343e-02
 5.86208066e-01 4.51270940e-01 4.04991894e-01 4.24507412e-04
 8.15929057e-01 7.93232554e-01 9.91986565e-01 3.64431776e-02
 3.28837706e-01 3.80889614e-05 1.81116916e+00 3.52274761e-02
 2.09019175e+00 2.60080270e+00 9.20625750e-02 7.70927864e-02
 2.73626603e+00 4.81980105e-02 6.10308422e-01 1.89769275e-01
 6.70566005e-01 3.28865485e-03 4.47699967e-01 4.11022648e-01
 9.71680102e-02 1.07081950e+00 1.72252465e-01 1.12395764e-01
 1.48753855e-01 1.79737995e+00 4.90755459e-01 4.22599664e+00
 7.00861513e-04 4.01555177e-01 4.37823068e-01 2.21559169e+00
 7.99156311e-01 8.26890334e-03 2.68670723e+00 1.69271308e+00
 4.52427471e-02 1.29573296e-01 1.62215714e-01 9.49160212e-01
 1.93695977e+00 3.93137044e-02 1.15749744e-01 2.06491579e+00
 4.31976220e-02 1.34659444e-03 4.00354431e+00 1.27813386e+00
 2.02155184e-02 6.67365201e-01 1.05022090e+00 5.19302642e-01
 1.01110981e+00 2.12400636e+00 1.74353831e-01 1.39903253e+00
 3.00218164e-01 1.00558456e+00 1.48405026e+00 7.62745576e+00
 8.93491914e-02 2.37129834e+00 1.26659402e+00 1.22300672e-04
 7.08727544e-02 5.77769545e-02 4.34455993e-02 9.19432256e-01
 5.12916465e-01 1.13243716e-01 8.74066052e-01 4.90483710e-01
 8.40734263e-02 9.89213569e-03 6.47630784e-02 1.15761939e-01
 1.43668879e-01 2.56440945e-01 7.31000702e-03 3.85262525e-02
 5.61291397e-01 1.53866097e-03 9.72220501e-03 7.05815454e+00
 2.48765428e+00 9.06442179e-02 7.96333794e-01 1.00202231e+00
 3.69424605e+00 5.79863615e-02 5.32695109e-02 9.30525151e-02
 6.86043924e-02 1.64740258e+00 4.58124234e-02 5.29701012e-02
 1.25896469e-01 4.57559752e-03 2.38889662e+00 3.78023448e-01
 9.52697198e-01 1.24165337e+00 3.85869736e-01 1.85438596e-02
 6.41114649e-01 3.90683827e-01 1.52299695e-03 4.60079842e-01
 2.49277693e-01 5.98883877e-01 3.46921996e-01 3.87921078e-02
 3.17446675e-01 2.82772025e+00 3.64481895e-01 4.68062760e-01
 5.64490854e+00 8.25068783e-04 6.70047666e-01 4.11952909e+00
 5.55600768e-01 3.49241389e-01 1.06192854e+00 1.52424412e-02
 2.03950247e+00 1.98434403e-01 6.73436339e-01 1.03190791e-01
 7.89652364e-01 8.54814035e-01 1.66112382e-01 9.60597185e-01
 1.48957834e+00 1.01620613e+00 8.91151090e-01 3.74515732e-01
 1.01566117e+00 8.26353311e-01 2.65748037e-01 4.78088897e-02
 1.03803567e-01 3.04105376e-01 6.09534867e-01 2.66480296e-01
 8.51709461e-02 1.75504074e-02 7.37392791e-01 4.45547627e-01
 1.01920051e+01 1.90397680e+00 1.19032925e-01 4.18345178e-01
 4.05814137e+00 4.65954808e-01 6.21346335e-01 1.96863524e-01
 1.86948466e+00 5.05861722e-01 2.00823721e+00 6.85555905e-02
 3.50967689e-03 1.14489696e+00 7.56860190e-01 1.65024454e-03
 5.25654713e-01 2.77816089e-01 4.14894897e+00 7.44884111e-01
 3.66930857e-01 3.34350662e-01 1.76704274e-02 1.01803604e-01
 1.50803182e+00 2.27782559e+00 5.39263376e-02 5.28864083e+00
 7.28501372e-01 6.35667763e-01 1.85287223e+00 2.07797688e-01
 1.04462975e+00 2.68653866e+00 1.70171382e+00 8.25434809e-01
 1.95739229e-01 5.86777015e-04 3.38523626e-01 6.70706186e-01
 6.91603718e-02 7.05415801e-01 5.41170451e-01 1.96423051e-01
 3.57583489e-01 7.72186040e-02 4.41547080e-01 2.73226048e-03
 1.15611345e+00 3.81414452e+00 4.80797920e-02 2.88144802e+00
 7.87614751e+00 4.09326613e-01 1.05969468e+00 5.82433154e-03
 1.27287116e+00 7.10243461e-02 7.72326236e+00 1.00702525e-01
 2.20963029e+00 1.54179324e+00 1.06498283e+00 2.81365286e-01
 4.26840365e+00 6.90745386e-01 1.08078109e+00 1.12815009e-01
 9.34503211e-01 3.77310691e-01 6.32148102e-01 1.48610950e+00
 3.86254124e-02 1.81354342e-01 7.08386724e-01 1.22883475e+00
 1.61091417e+00 7.22395621e-01 2.12022207e-01 5.64460618e-01
 5.63984628e-01 2.00420333e+00 1.97218897e+00 9.52994497e-02
 4.87172588e-01 9.51395302e-02 5.18402335e-01 1.09815479e-01
 2.75675393e+00 4.95546420e-01 3.24699636e-01 2.58775197e+00
 2.91266830e+00 4.73221106e-01 1.81319646e+00 1.07927857e+00
 3.89552417e-04 1.62196448e-01 6.80368197e-01 2.52353669e-01
 3.26154616e-01 8.64469404e-01 3.32897027e-01 9.56447553e-02
 4.24908995e-01 3.78155423e-01 2.61840137e-01 4.04339278e-01
 1.65512938e+00 1.09538057e+00 1.87428695e+00 8.64276432e-01
 1.73504824e-02 4.72831874e-01 5.84834954e-04 1.38305653e+00
 1.23181570e-01 2.07253507e-01 7.61820423e+00 8.06597674e-02
 2.36253323e-01 1.34883222e-02 9.13465393e-02 1.24192269e-01
 2.48078052e+00 4.07978606e-02 2.74520120e+00 1.44432368e-01
 1.49951291e-01 4.00160128e-01 9.19826286e-01 5.55520487e-01
 5.32465979e+00 5.28801618e-02 2.25809549e-01 2.90058005e+00
 4.59071611e+00 2.51528781e+00 2.25971683e-01 1.94577862e+00
 4.13835631e-02 1.53168313e+00 1.82281699e+00 1.10417063e+00
 2.36483981e-03 3.69841310e-01 1.46772028e-01 7.90380553e-01
 9.33261422e+00 1.34604751e-01 4.59773701e-02 7.44594670e-02
 1.62301313e+00 9.90375892e-02 4.82544177e-03 2.81306978e-01
 2.31919356e-02 2.13679196e+00 2.51848677e-01 1.22052575e+00
 9.87307928e-01 4.09983939e-01 2.04925833e-01 4.38387902e+00
 1.95639467e-03 1.00469831e+00 7.99048080e-02 2.79394345e+00
 7.26960427e-01 1.24164050e-03 3.83268128e+00 8.90292276e-01
 4.12366015e-02 2.25215434e+00 4.00577677e-03 1.46976610e-01
 1.71427715e-02 1.01817821e-02 5.36783322e-01 1.22515621e-01
 1.12052739e+00 7.53448335e+00 2.29807023e-01 6.75935160e-01
 5.99748971e-01 1.42931661e-01 1.43994327e+00 5.93956946e-01
 2.78257447e+00 2.27151083e-01 1.16149542e-01 1.50649162e-02]
Mean 1.0161020407575565
SD 1.5424878347480442
Range 10.191966986881113

### Reshape

In [41]:
vector.shape

(500,)

In [42]:
################################将一维向量vector转成大小为500*1的二维向量并赋值给row_vector################################## 
row_vector = vector.reshape(-1,1)
################################将一维向量vector转成大小为500*1的二维向量并赋值给row_vector################################## 
row_vector.shape
print(row_vector)

[[2.37790160e-03]
 [4.94903951e-05]
 [6.46828766e-01]
 [1.32283727e-01]
 [2.28800215e-01]
 [8.06225934e-01]
 [2.67146169e-04]
 [1.11378924e-01]
 [7.97062954e-01]
 [8.89663700e-01]
 [2.35863991e-01]
 [1.00758560e+00]
 [1.92579421e+00]
 [1.90843549e-01]
 [1.40523131e+00]
 [8.25794809e-01]
 [9.48739614e-02]
 [6.19796205e-02]
 [6.34424155e-03]
 [2.46532919e-01]
 [5.26347411e-01]
 [1.18722896e-01]
 [2.02085434e+00]
 [4.27865652e-01]
 [1.36179133e+00]
 [1.39358778e-01]
 [3.96333372e+00]
 [1.95011587e+00]
 [6.88951450e-02]
 [1.12314811e-01]
 [5.12783599e+00]
 [7.90283979e-01]
 [2.04495142e-02]
 [2.24568002e+00]
 [1.08157986e-01]
 [3.38975536e-05]
 [2.76337249e-01]
 [8.59476519e-02]
 [6.77722695e-01]
 [1.97194784e-01]
 [2.40451410e+00]
 [3.51015977e-01]
 [4.86116234e-01]
 [2.23372339e+00]
 [1.74109052e-01]
 [6.65692316e-06]
 [4.47359583e-03]
 [8.61652531e-02]
 [6.22560091e-03]
 [6.73274991e+00]
 [3.76331129e-01]
 [1.13856776e-03]
 [1.54576159e-02]
 [8.36454362e-01]
 [5.47257784e-01]
 [5.68271466e-01]
 [4.52913898e-01]
 [1.70309378e-01]
 [1.90711915e+00]
 [1.63948919e-01]
 [1.12388909e+00]
 [1.10627177e-01]
 [4.90558320e-02]
 [1.64202501e+00]
 [6.30588647e-01]
 [1.00493323e+00]
 [1.96593874e-04]
 [1.94783378e+00]
 [8.43551120e-02]
 [1.41212618e-01]
 [8.15312695e-01]
 [6.04784841e-01]
 [2.14301426e-01]
 [1.94722419e-01]
 [4.97310889e-01]
 [1.21359563e+00]
 [6.86396661e-02]
 [1.05296379e+00]
 [2.96981344e+00]
 [1.90212674e+00]
 [2.31027123e-02]
 [1.36552531e-01]
 [6.88541185e-01]
 [7.42094410e-02]
 [1.01249333e+00]
 [2.90206583e-01]
 [1.02850072e-01]
 [1.04645377e+00]
 [4.74865824e-01]
 [2.45005803e-04]
 [5.44798880e-02]
 [1.53853919e-02]
 [7.90168169e-01]
 [1.21178431e-02]
 [2.85774669e-01]
 [1.65538355e+00]
 [1.07965113e+00]
 [1.91906782e+00]
 [1.72688371e+00]
 [1.75988305e+00]
 [4.70933174e-01]
 [5.76560779e-01]
 [2.59998955e-01]
 [2.87258934e+00]
 [7.02377802e-01]
 [9.42114975e-01]
 [1.70236609e-02]
 [2.83710929e+00]
 [3.75716750e+00]
 [3.55809119e-02]
 [1.18648540e-02]
 [8.80217505e-02]
 [8.33554394e+00]
 [4.17393749e-01]
 [7.37596096e-01]
 [3.52481401e-01]
 [1.60718214e-02]
 [6.40427715e-01]
 [1.05193848e-02]
 [2.74838193e-01]
 [2.68250776e-01]
 [8.22414638e-03]
 [1.63269644e-02]
 [1.35334023e-01]
 [1.80695300e-02]
 [4.77506700e+00]
 [1.61294725e-01]
 [2.35231546e+00]
 [1.10141922e+00]
 [2.77513675e-01]
 [9.69641879e-01]
 [2.92082391e+00]
 [1.59761993e+00]
 [9.26813514e-01]
 [3.00618602e-01]
 [4.27712133e-01]
 [2.90371144e+00]
 [2.34497869e-02]
 [1.85462497e+00]
 [1.57388651e+00]
 [1.64677735e+00]
 [5.02453788e-01]
 [3.97718794e-01]
 [1.02191533e+00]
 [7.82549643e+00]
 [1.03166297e+00]
 [2.43534867e-01]
 [1.16237786e-01]
 [2.71638344e+00]
 [1.21998058e-02]
 [5.93949585e-01]
 [3.86101769e-01]
 [7.69992991e-02]
 [2.20379086e-01]
 [4.23049392e+00]
 [3.33563127e-01]
 [2.97198775e-01]
 [1.72572934e+00]
 [1.67021244e+00]
 [5.48724160e-01]
 [2.14227439e-01]
 [1.08588506e-02]
 [2.50548255e+00]
 [1.11990992e-02]
 [8.42950191e-01]
 [2.12088673e-04]
 [1.67104048e-01]
 [2.50662760e-01]
 [1.74342715e+00]
 [1.75717422e-02]
 [9.71739447e-01]
 [3.81077082e-01]
 [1.18272638e+00]
 [1.19243667e+00]
 [5.68947128e-01]
 [9.33037919e-02]
 [8.78437298e-01]
 [3.26519562e-01]
 [8.60222337e-01]
 [1.29431562e+00]
 [2.19337034e+00]
 [8.70830030e-01]
 [1.59515618e+00]
 [8.54300068e-04]
 [3.46282799e-01]
 [7.23943333e-05]
 [7.34242795e-01]
 [1.75842046e+00]
 [5.82905030e+00]
 [2.93957005e-01]
 [7.47695904e-02]
 [1.08094020e+00]
 [7.19813022e-01]
 [4.36998695e-01]
 [3.22108987e-02]
 [6.23736560e+00]
 [4.10494975e-01]
 [2.88119055e+00]
 [2.23964765e-01]
 [2.92707206e-05]
 [1.09164697e+00]
 [4.05071201e-03]
 [1.64460301e-01]
 [2.15421175e-02]
 [2.38016387e-01]
 [2.09642926e+00]
 [5.92057219e-03]
 [1.39379762e-01]
 [2.90980795e+00]
 [1.22018846e-02]
 [8.57505382e-01]
 [2.38157278e+00]
 [5.37322174e-01]
 [3.02114479e-01]
 [3.26894316e-01]
 [2.22054572e-01]
 [2.80880700e+00]
 [5.55721835e-02]
 [1.66836298e+00]
 [5.38966480e-01]
 [5.50203170e+00]
 [4.41695153e-01]
 [1.79011772e+00]
 [1.20815878e+00]
 [2.75556517e-02]
 [6.22983679e-01]
 [3.12143942e-01]
 [3.01638635e-01]
 [3.65999508e-01]
 [2.37269470e+00]
 [2.18811014e-02]
 [1.41047063e+00]
 [2.58242104e+00]
 [3.35882970e-02]
 [2.26502333e+00]
 [2.32996775e-02]
 [4.07400122e-01]
 [2.07454626e+00]
 [3.23325728e-01]
 [5.32419073e-02]
 [2.60294003e-01]
 [2.38374823e+00]
 [6.12985618e-01]
 [1.70942521e-02]
 [7.07257486e-02]
 [1.26661262e-01]
 [4.37560045e-01]
 [3.02546062e-01]
 [7.61021043e-01]
 [9.41971278e-01]
 [1.65602668e+00]
 [2.58986416e+00]
 [5.90180102e-02]
 [4.66583952e-02]
 [3.79749679e-01]
 [1.58156691e+00]
 [8.51999568e+00]
 [9.67048939e-01]
 [8.32150174e-01]
 [2.29011822e-02]
 [1.74855485e+00]
 [4.14926087e-01]
 [1.82352657e+00]
 [6.92839529e-01]
 [3.95173042e-01]
 [4.93651703e-01]
 [2.26055370e-04]
 [2.67983350e+00]
 [5.76825318e-01]
 [1.33734032e-01]
 [2.59228433e-01]
 [1.52841842e+00]
 [1.01730736e-01]
 [2.50487232e+00]
 [3.88334420e+00]
 [4.96768177e-02]
 [1.17334818e+00]
 [1.57574497e+00]
 [4.65639904e-02]
 [7.08764438e-01]
 [1.13211482e+00]
 [1.02291344e-01]
 [1.72094561e+00]
 [9.53048084e-01]
 [5.88861022e+00]
 [3.36048826e+00]
 [6.80250712e+00]
 [1.82579825e-03]
 [8.91097044e-02]
 [3.61904405e+00]
 [1.31361280e+00]
 [1.49871359e-01]
 [9.68535964e-01]
 [1.88949109e+00]
 [6.78736997e-01]
 [9.23548794e-01]
 [7.85293610e-01]
 [1.09311200e-01]
 [1.81799609e-01]
 [3.01298365e+00]
 [8.66892152e-01]
 [1.87512350e+00]
 [2.08764021e-02]
 [1.14593043e+00]
 [3.58834157e-01]
 [1.53755303e+00]
 [6.85259897e-01]
 [7.52440403e-01]
 [4.80659575e-02]
 [3.54155481e-01]
 [8.57795332e-02]
 [1.52755641e+00]
 [1.23736035e+00]
 [9.74002860e-01]
 [3.49967696e+00]
 [3.08833743e-01]
 [8.52821138e-02]
 [1.24184214e+00]
 [4.17457853e-01]
 [1.94818157e-01]
 [3.84660000e+00]
 [1.35409497e+00]
 [9.68736524e-04]
 [1.99963374e+00]
 [1.03565191e+00]
 [4.05878444e-01]
 [8.20557476e-02]
 [1.86630034e+00]
 [7.33311854e-01]
 [1.94871199e+00]
 [2.33539877e-02]
 [2.12130054e+00]
 [3.04323694e+00]
 [7.24755341e-01]
 [6.97398573e-01]
 [1.26438461e+00]
 [1.64409896e-01]
 [5.26009796e-02]
 [1.16719788e+00]
 [3.45244613e-01]
 [6.14672172e-01]
 [3.28896757e-01]
 [3.16473113e-01]
 [4.17812275e+00]
 [2.24370079e-02]
 [8.71360626e-01]
 [3.76441776e-02]
 [8.20722432e-01]
 [6.69965470e-01]
 [2.37137898e+00]
 [1.18944057e-01]
 [9.28480822e+00]
 [9.01452923e-01]
 [1.61540852e+00]
 [4.87676595e-01]
 [4.62620480e-03]
 [1.34766423e-01]
 [6.33514251e-02]
 [6.40813307e+00]
 [1.88626147e-01]
 [3.98012005e+00]
 [1.67755999e+00]
 [9.29436402e-01]
 [6.94290187e-02]
 [4.51217736e-02]
 [4.61307737e-04]
 [1.21306640e-02]
 [8.54943872e-02]
 [4.05402353e-03]
 [1.66826668e-02]
 [1.41790572e-02]
 [4.08940728e+00]
 [7.42960706e-01]
 [5.99728138e-01]
 [8.98808417e-01]
 [1.70682697e-01]
 [3.53580924e-01]
 [4.96003749e-02]
 [2.93539995e+00]
 [2.42203520e-03]
 [2.33303616e+00]
 [2.01371012e+00]
 [9.66879404e-01]
 [8.70853646e-02]
 [6.45334575e-01]
 [7.16524734e-01]
 [1.41402768e-02]
 [5.12961385e-01]
 [2.17882373e-01]
 [1.39441158e+00]
 [7.17246208e-01]
 [8.34297957e-01]
 [5.93822743e-03]
 [2.76649788e-01]
 [6.79316803e-01]
 [4.09675073e-01]
 [3.44250209e-02]
 [2.48331327e-01]
 [7.93915647e-01]
 [1.66628008e-01]
 [3.86844661e-02]
 [8.84515370e-01]
 [9.93621792e-01]
 [6.35411971e-01]
 [3.94326739e-01]
 [3.07964883e-01]
 [5.59213898e-01]
 [1.09856602e+00]
 [9.99437172e-01]
 [4.02472618e-01]
 [2.98214456e+00]
 [1.59292766e+00]
 [2.21751232e+00]
 [7.30618543e-01]
 [6.48327268e-01]
 [5.13154852e+00]
 [1.10096430e+00]
 [3.51775710e+00]
 [6.17711035e+00]
 [1.38090401e+00]
 [9.50434889e-02]
 [2.01060950e-01]
 [1.86007589e-01]
 [6.53446836e-01]
 [9.38017548e-02]
 [2.08716965e+00]
 [8.95613984e-02]
 [2.43164747e-01]
 [3.27648055e-02]
 [8.58474434e-01]
 [8.44644292e-02]
 [6.52178860e-01]
 [1.70487640e+00]
 [8.36077850e-01]
 [6.33757034e-02]
 [6.27768268e-05]
 [4.28594603e+00]
 [2.83141841e-01]
 [8.20788125e-01]
 [1.64369765e+00]
 [3.99631267e-01]
 [5.94759283e-01]
 [3.56194814e-01]
 [3.69837229e-01]
 [5.84394202e-01]
 [1.73608776e+00]
 [3.07376653e-01]
 [6.70633077e+00]
 [3.58270972e-02]
 [2.42650697e-02]
 [3.67963023e+00]
 [5.39121367e-02]
 [3.61013277e-02]
 [8.22086549e-01]
 [2.66737083e+00]
 [6.73433018e-01]
 [1.13077160e-01]
 [2.22731565e+00]
 [6.81665618e-02]
 [1.16016279e+00]
 [6.36668487e-03]
 [4.56414610e-01]
 [3.89833560e-03]
 [1.32082155e+00]
 [7.56962602e-02]
 [3.11698022e-02]
 [2.63805793e+00]
 [1.02462842e+00]
 [2.59120577e-01]
 [3.02986991e+00]
 [2.76265863e+00]
 [7.94190137e-02]
 [1.09194090e+00]
 [5.44720327e-02]
 [1.77263443e-01]
 [5.20879667e-01]
 [2.87056244e+00]
 [1.77500925e-01]
 [1.66454339e-02]
 [1.76174153e-01]
 [3.84027347e-03]
 [2.45620522e-01]
 [5.40047820e-01]
 [8.15131070e+00]
 [3.93227915e-01]
 [4.24389323e-04]
 [3.60489868e-01]
 [6.09029881e-04]
 [2.73699847e-01]
 [7.36690592e-05]
 [2.48425217e-01]
 [3.14281113e-01]
 [9.17856416e+00]
 [1.46289884e+00]
 [2.90063470e-01]
 [8.03041455e-01]
 [1.20284956e+00]
 [3.60870545e+00]
 [1.80261958e+00]
 [5.62397449e+00]]

In [43]:
col_vector = vector.reshape(1,-1)
col_vector.shape

(1, 500)

In [44]:
################################将一维向量vector转成大小为10*50的二维向量并赋值给maxtrix################################## 
matrix = vector.reshape(10,50)
################################将一维向量vector转成大小为10*50的二维向量并赋值给maxtrix################################## 
matrix.shape
print(matrix)

[[2.37790160e-03 4.94903951e-05 6.46828766e-01 1.32283727e-01
  2.28800215e-01 8.06225934e-01 2.67146169e-04 1.11378924e-01
  7.97062954e-01 8.89663700e-01 2.35863991e-01 1.00758560e+00
  1.92579421e+00 1.90843549e-01 1.40523131e+00 8.25794809e-01
  9.48739614e-02 6.19796205e-02 6.34424155e-03 2.46532919e-01
  5.26347411e-01 1.18722896e-01 2.02085434e+00 4.27865652e-01
  1.36179133e+00 1.39358778e-01 3.96333372e+00 1.95011587e+00
  6.88951450e-02 1.12314811e-01 5.12783599e+00 7.90283979e-01
  2.04495142e-02 2.24568002e+00 1.08157986e-01 3.38975536e-05
  2.76337249e-01 8.59476519e-02 6.77722695e-01 1.97194784e-01
  2.40451410e+00 3.51015977e-01 4.86116234e-01 2.23372339e+00
  1.74109052e-01 6.65692316e-06 4.47359583e-03 8.61652531e-02
  6.22560091e-03 6.73274991e+00]
 [3.76331129e-01 1.13856776e-03 1.54576159e-02 8.36454362e-01
  5.47257784e-01 5.68271466e-01 4.52913898e-01 1.70309378e-01
  1.90711915e+00 1.63948919e-01 1.12388909e+00 1.10627177e-01
  4.90558320e-02 1.64202501e+00 6.30588647e-01 1.00493323e+00
  1.96593874e-04 1.94783378e+00 8.43551120e-02 1.41212618e-01
  8.15312695e-01 6.04784841e-01 2.14301426e-01 1.94722419e-01
  4.97310889e-01 1.21359563e+00 6.86396661e-02 1.05296379e+00
  2.96981344e+00 1.90212674e+00 2.31027123e-02 1.36552531e-01
  6.88541185e-01 7.42094410e-02 1.01249333e+00 2.90206583e-01
  1.02850072e-01 1.04645377e+00 4.74865824e-01 2.45005803e-04
  5.44798880e-02 1.53853919e-02 7.90168169e-01 1.21178431e-02
  2.85774669e-01 1.65538355e+00 1.07965113e+00 1.91906782e+00
  1.72688371e+00 1.75988305e+00]
 [4.70933174e-01 5.76560779e-01 2.59998955e-01 2.87258934e+00
  7.02377802e-01 9.42114975e-01 1.70236609e-02 2.83710929e+00
  3.75716750e+00 3.55809119e-02 1.18648540e-02 8.80217505e-02
  8.33554394e+00 4.17393749e-01 7.37596096e-01 3.52481401e-01
  1.60718214e-02 6.40427715e-01 1.05193848e-02 2.74838193e-01
  2.68250776e-01 8.22414638e-03 1.63269644e-02 1.35334023e-01
  1.80695300e-02 4.77506700e+00 1.61294725e-01 2.35231546e+00
  1.10141922e+00 2.77513675e-01 9.69641879e-01 2.92082391e+00
  1.59761993e+00 9.26813514e-01 3.00618602e-01 4.27712133e-01
  2.90371144e+00 2.34497869e-02 1.85462497e+00 1.57388651e+00
  1.64677735e+00 5.02453788e-01 3.97718794e-01 1.02191533e+00
  7.82549643e+00 1.03166297e+00 2.43534867e-01 1.16237786e-01
  2.71638344e+00 1.21998058e-02]
 [5.93949585e-01 3.86101769e-01 7.69992991e-02 2.20379086e-01
  4.23049392e+00 3.33563127e-01 2.97198775e-01 1.72572934e+00
  1.67021244e+00 5.48724160e-01 2.14227439e-01 1.08588506e-02
  2.50548255e+00 1.11990992e-02 8.42950191e-01 2.12088673e-04
  1.67104048e-01 2.50662760e-01 1.74342715e+00 1.75717422e-02
  9.71739447e-01 3.81077082e-01 1.18272638e+00 1.19243667e+00
  5.68947128e-01 9.33037919e-02 8.78437298e-01 3.26519562e-01
  8.60222337e-01 1.29431562e+00 2.19337034e+00 8.70830030e-01
  1.59515618e+00 8.54300068e-04 3.46282799e-01 7.23943333e-05
  7.34242795e-01 1.75842046e+00 5.82905030e+00 2.93957005e-01
  7.47695904e-02 1.08094020e+00 7.19813022e-01 4.36998695e-01
  3.22108987e-02 6.23736560e+00 4.10494975e-01 2.88119055e+00
  2.23964765e-01 2.92707206e-05]
 [1.09164697e+00 4.05071201e-03 1.64460301e-01 2.15421175e-02
  2.38016387e-01 2.09642926e+00 5.92057219e-03 1.39379762e-01
  2.90980795e+00 1.22018846e-02 8.57505382e-01 2.38157278e+00
  5.37322174e-01 3.02114479e-01 3.26894316e-01 2.22054572e-01
  2.80880700e+00 5.55721835e-02 1.66836298e+00 5.38966480e-01
  5.50203170e+00 4.41695153e-01 1.79011772e+00 1.20815878e+00
  2.75556517e-02 6.22983679e-01 3.12143942e-01 3.01638635e-01
  3.65999508e-01 2.37269470e+00 2.18811014e-02 1.41047063e+00
  2.58242104e+00 3.35882970e-02 2.26502333e+00 2.32996775e-02
  4.07400122e-01 2.07454626e+00 3.23325728e-01 5.32419073e-02
  2.60294003e-01 2.38374823e+00 6.12985618e-01 1.70942521e-02
  7.07257486e-02 1.26661262e-01 4.37560045e-01 3.02546062e-01
  7.61021043e-01 9.41971278e-01]
 [1.65602668e+00 2.58986416e+00 5.90180102e-02 4.66583952e-02
  3.79749679e-01 1.58156691e+00 8.51999568e+00 9.67048939e-01
  8.32150174e-01 2.29011822e-02 1.74855485e+00 4.14926087e-01
  1.82352657e+00 6.92839529e-01 3.95173042e-01 4.93651703e-01
  2.26055370e-04 2.67983350e+00 5.76825318e-01 1.33734032e-01
  2.59228433e-01 1.52841842e+00 1.01730736e-01 2.50487232e+00
  3.88334420e+00 4.96768177e-02 1.17334818e+00 1.57574497e+00
  4.65639904e-02 7.08764438e-01 1.13211482e+00 1.02291344e-01
  1.72094561e+00 9.53048084e-01 5.88861022e+00 3.36048826e+00
  6.80250712e+00 1.82579825e-03 8.91097044e-02 3.61904405e+00
  1.31361280e+00 1.49871359e-01 9.68535964e-01 1.88949109e+00
  6.78736997e-01 9.23548794e-01 7.85293610e-01 1.09311200e-01
  1.81799609e-01 3.01298365e+00]
 [8.66892152e-01 1.87512350e+00 2.08764021e-02 1.14593043e+00
  3.58834157e-01 1.53755303e+00 6.85259897e-01 7.52440403e-01
  4.80659575e-02 3.54155481e-01 8.57795332e-02 1.52755641e+00
  1.23736035e+00 9.74002860e-01 3.49967696e+00 3.08833743e-01
  8.52821138e-02 1.24184214e+00 4.17457853e-01 1.94818157e-01
  3.84660000e+00 1.35409497e+00 9.68736524e-04 1.99963374e+00
  1.03565191e+00 4.05878444e-01 8.20557476e-02 1.86630034e+00
  7.33311854e-01 1.94871199e+00 2.33539877e-02 2.12130054e+00
  3.04323694e+00 7.24755341e-01 6.97398573e-01 1.26438461e+00
  1.64409896e-01 5.26009796e-02 1.16719788e+00 3.45244613e-01
  6.14672172e-01 3.28896757e-01 3.16473113e-01 4.17812275e+00
  2.24370079e-02 8.71360626e-01 3.76441776e-02 8.20722432e-01
  6.69965470e-01 2.37137898e+00]
 [1.18944057e-01 9.28480822e+00 9.01452923e-01 1.61540852e+00
  4.87676595e-01 4.62620480e-03 1.34766423e-01 6.33514251e-02
  6.40813307e+00 1.88626147e-01 3.98012005e+00 1.67755999e+00
  9.29436402e-01 6.94290187e-02 4.51217736e-02 4.61307737e-04
  1.21306640e-02 8.54943872e-02 4.05402353e-03 1.66826668e-02
  1.41790572e-02 4.08940728e+00 7.42960706e-01 5.99728138e-01
  8.98808417e-01 1.70682697e-01 3.53580924e-01 4.96003749e-02
  2.93539995e+00 2.42203520e-03 2.33303616e+00 2.01371012e+00
  9.66879404e-01 8.70853646e-02 6.45334575e-01 7.16524734e-01
  1.41402768e-02 5.12961385e-01 2.17882373e-01 1.39441158e+00
  7.17246208e-01 8.34297957e-01 5.93822743e-03 2.76649788e-01
  6.79316803e-01 4.09675073e-01 3.44250209e-02 2.48331327e-01
  7.93915647e-01 1.66628008e-01]
 [3.86844661e-02 8.84515370e-01 9.93621792e-01 6.35411971e-01
  3.94326739e-01 3.07964883e-01 5.59213898e-01 1.09856602e+00
  9.99437172e-01 4.02472618e-01 2.98214456e+00 1.59292766e+00
  2.21751232e+00 7.30618543e-01 6.48327268e-01 5.13154852e+00
  1.10096430e+00 3.51775710e+00 6.17711035e+00 1.38090401e+00
  9.50434889e-02 2.01060950e-01 1.86007589e-01 6.53446836e-01
  9.38017548e-02 2.08716965e+00 8.95613984e-02 2.43164747e-01
  3.27648055e-02 8.58474434e-01 8.44644292e-02 6.52178860e-01
  1.70487640e+00 8.36077850e-01 6.33757034e-02 6.27768268e-05
  4.28594603e+00 2.83141841e-01 8.20788125e-01 1.64369765e+00
  3.99631267e-01 5.94759283e-01 3.56194814e-01 3.69837229e-01
  5.84394202e-01 1.73608776e+00 3.07376653e-01 6.70633077e+00
  3.58270972e-02 2.42650697e-02]
 [3.67963023e+00 5.39121367e-02 3.61013277e-02 8.22086549e-01
  2.66737083e+00 6.73433018e-01 1.13077160e-01 2.22731565e+00
  6.81665618e-02 1.16016279e+00 6.36668487e-03 4.56414610e-01
  3.89833560e-03 1.32082155e+00 7.56962602e-02 3.11698022e-02
  2.63805793e+00 1.02462842e+00 2.59120577e-01 3.02986991e+00
  2.76265863e+00 7.94190137e-02 1.09194090e+00 5.44720327e-02
  1.77263443e-01 5.20879667e-01 2.87056244e+00 1.77500925e-01
  1.66454339e-02 1.76174153e-01 3.84027347e-03 2.45620522e-01
  5.40047820e-01 8.15131070e+00 3.93227915e-01 4.24389323e-04
  3.60489868e-01 6.09029881e-04 2.73699847e-01 7.36690592e-05
  2.48425217e-01 3.14281113e-01 9.17856416e+00 1.46289884e+00
  2.90063470e-01 8.03041455e-01 1.20284956e+00 3.60870545e+00
  1.80261958e+00 5.62397449e+00]]

### Pivot Table

In [45]:
#Determine pivot table
df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
                       "bar", "bar", "bar", "bar"],
                    "B": ["one", "one", "one", "two", "two",
                          "one", "one", "two", "two"],
                    "C": ["small", "large", "large", "small",
                          "small", "large", "small", "small",
                          "large"],
                    "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
                    "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})

In [46]:
df.head(9)

     A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

In [47]:
###################################想办法生成以下表格，行为A、B，列为C###################################
table = pivot_table(df, values='D', index=['A', 'B'],
                  columns=['C'], aggfunc=np.sum)

###################################想办法生成以下表格，行为A、B，列为C###################################
table

C        large  small
A   B
bar one    4.0    5.0
    two    7.0    6.0
foo one    4.0    1.0
    two    NaN    6.0

### Merging dataframes

In [48]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                       index=[0, 1, 2, 3])
    

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                       index=[4, 5, 6, 7])
    

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                       'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                       index=[8, 9, 10, 11])
    
###################################将df1,df2,df3按行拼接到一起，并赋给result###################################
frames = [df1, df2, df3]

result = pd.concat(frames)

###################################将df1,df2,df3按行拼接到一起，并赋给result####################################

print(result)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11